apiVersion: v1
kind: Service
metadata:
  name: rm-deployment
spec:
  type: {{ .Values.service.type }}
  selector:
    app: rm-api
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
