services:
  db:
    image: postgres:16
    container_name: my-postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: rmapi
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  rediscache:
    image: valkey/valkey:8
    ports:
      - "6379:6379"
volumes:
  pgdata: